In [16]:
import numpy as np
from scipy.linalg import eig
from sympy import (
    Eq,
    solve,
    symbols
)

Uma equação linear e de fato uma fórmula onde todas as variáveis (dependentes ou independentes) estão elevadas à primeira potência e estão associadas a apenas uma constante. Elas não estão elevadas a 2 ou superior.

Exemplo:

$3x+2y=15$

$−2x+4y = 7$

In [11]:
x, y = symbols('x y')

In [12]:
# Definindo as equações
eq1 = Eq(3*x + 2*y, 15)
eq2 = Eq(-2*x + 4*y, 7)

In [13]:
# Resolvendo o sistema de equações
solucao = solve((eq1, eq2),
                (x, y))

In [14]:
# Exibindo a solução
print("Solução:")
print(solucao)

Solução:
{x: 23/8, y: 51/16}


# Autovalores e Autovetores

O Autovalor descreve o quão "esticado" (λ > 0) ou "comprimido" (λ < 0) está o autovetor, e se a direção do autovetor está preservada ou revertida.

In [25]:
matriz = np.array([[1, 2, 3],
              [3, 2, 1],
              [3, 2, 1]])

In [ ]:
autovalores, autovetores = eig(matriz)

In [26]:
print("Autovalores:", autovalores)

Autovalores: [-2.+0.j  6.+0.j  0.+0.j]


In [28]:
print("Autovetores:\n", autovetores)

Autovetores:
 [[-0.76249285  0.57735027  0.40824829]
 [ 0.45749571  0.57735027 -0.81649658]
 [ 0.45749571  0.57735027  0.40824829]]
