In [1]:
from sklearn.model_selection import LeaveOneOut

In [2]:
X = [1, 2, 3, 4]
loo = LeaveOneOut()
for train, test in loo.split(X):
    print("%s %s" % (train, test))

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


## Outro Exemplo

In [4]:
from sklearn.model_selection import KFold
import numpy as np

In [5]:
X = ["a", "b", "c", "d"]
kf = KFold(n_splits=4)
for train, test in kf.split(X):
    #Add here the model for training
    print("%s %s" % (train, test))

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


In [6]:
X = np.array([[0., 0.],
              [1., 1.],
              [-1., -1.],
              [2., 2.]])

y = np.array([0, 1, 0, 1])

X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]

In [7]:
X_train

array([[ 0.,  0.],
       [ 1.,  1.],
       [-1., -1.]])

In [8]:
X_test

array([[2., 2.]])

In [9]:
y_train

array([0, 1, 0])

In [10]:
y_test

array([1])